#!/usr/bin/env bash
#Install Nginx and the int file have only a message
sudo apt update -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i 's/listen 80 default_server/listen 80/g' /etc/nginx/sites-available/default
sudo service nginx restart
