#!/usr/bin/env bash
#Install Nginx and the int file have only a message
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" >  /var/www/html/index.nginx-debian.html
service nginx start

